// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { existsSync } from "fs"
import { config } from "dotenv"
import { defineConfig } from "prisma/config"

// Load environment variables from .env.local if it exists (local dev)
// In CI, environment variables are already set
if (existsSync(".env.local")) {
  config({ path: ".env.local" })
}

// For prisma generate, we don't need a real database URL
// Use a dummy URL if DATABASE_URL is not set (CI jobs without DB service)
const databaseUrl =
  process.env.DATABASE_URL || "postgresql://dummy:dummy@localhost:5432/dummy?schema=public"

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
})
