/**
 * System Registry Declarations
 *
 * THIS IS THE CANONICAL SOURCE OF TRUTH for what components exist in FiskAI.
 *
 * GOVERNANCE RULES:
 * - CRITICAL components MUST have owner !== null
 * - New components MUST be added here before merging
 * - Component IDs are STABLE and NEVER change
 * - Use aliases[] if a component is renamed
 *
 * Generated from observed-inventory.json on 2025-12-28
 * Then curated with owners, dependencies, and critical paths.
 */

import type { SystemComponent, CriticalPath } from "./schema"

// =============================================================================
// CRITICAL PATHS
// =============================================================================

export const CRITICAL_PATHS: CriticalPath[] = [
  {
    pathId: "path-fiscalization",
    name: "Fiscalization Path",
    components: [
      "module-fiscalization",
      "lib-fiscal",
      "integration-fina-cis",
      "job-fiscal-processor",
      "job-fiscal-retry",
      "job-certificate-check",
    ],
    reason: "Legal requirement - invoice fiscalization with Croatian Tax Authority",
    sloTarget: "99.9% success rate, <5s processing time",
  },
  {
    pathId: "path-billing",
    name: "Billing Path",
    components: [
      "route-group-billing",
      "lib-billing",
      "integration-stripe",
      "route-group-webhooks",
    ],
    reason: "Money movement - subscription billing and payment processing",
    sloTarget: "99.95% uptime, webhooks processed <30s",
  },
  {
    pathId: "path-rtl-pipeline",
    name: "Regulatory Truth Layer Pipeline",
    components: [
      "worker-sentinel",
      "queue-sentinel",
      "worker-extractor",
      "queue-extract",
      "worker-ocr",
      "queue-ocr",
      "worker-composer",
      "queue-compose",
      "worker-reviewer",
      "queue-review",
      "worker-arbiter",
      "queue-arbiter",
      "worker-releaser",
      "queue-release",
    ],
    reason: "Core regulatory content processing pipeline",
    sloTarget: "Queue lag <1h, daily processing complete by 06:00 CET",
  },
  {
    pathId: "path-authentication",
    name: "Authentication Path",
    components: ["route-group-auth", "route-group-webauthn", "lib-auth", "store-postgresql"],
    reason: "Security boundary - user authentication and session management",
    sloTarget: "99.99% uptime, <500ms login latency",
  },
]

// =============================================================================
// UI PORTALS
// =============================================================================

export const UI_COMPONENTS: SystemComponent[] = [
  {
    componentId: "ui-portal-marketing",
    type: "UI",
    name: "Marketing Portal",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: "docs/product-bible/05-UI-EXPERIENCE.md",
    codeRef: "src/app/(marketing)/",
    dependencies: [],
    criticalPaths: [],
  },
  {
    componentId: "ui-portal-app",
    type: "UI",
    name: "Client App Portal",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:platform",
    docsRef: "docs/product-bible/05-UI-EXPERIENCE.md",
    codeRef: "src/app/(app)/",
    dependencies: [
      { componentId: "lib-auth", type: "SECURITY" },
      { componentId: "lib-modules", type: "HARD" },
      { componentId: "lib-visibility", type: "HARD" },
      { componentId: "store-postgresql", type: "HARD" },
    ],
    criticalPaths: ["path-authentication"],
  },
  {
    componentId: "ui-portal-staff",
    type: "UI",
    name: "Staff Portal",
    status: "BETA",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: "docs/02_FEATURES/features/staff-portal.md",
    codeRef: "src/app/(staff)/",
    dependencies: [
      { componentId: "lib-auth", type: "SECURITY" },
      { componentId: "store-postgresql", type: "HARD" },
    ],
    criticalPaths: [],
  },
  {
    componentId: "ui-portal-admin",
    type: "UI",
    name: "Admin Portal",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/(admin)/",
    dependencies: [
      { componentId: "lib-auth", type: "SECURITY" },
      { componentId: "store-postgresql", type: "HARD" },
    ],
    criticalPaths: [],
  },
]

// =============================================================================
// MODULES
// =============================================================================

export const MODULE_COMPONENTS: SystemComponent[] = [
  {
    componentId: "module-platform-core",
    type: "MODULE",
    name: "Platform Core",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/modules/definitions.ts",
    dependencies: [
      { componentId: "lib-auth", type: "HARD" },
      { componentId: "store-postgresql", type: "HARD" },
    ],
    criticalPaths: [],
  },
  {
    componentId: "module-invoicing",
    type: "MODULE",
    name: "Invoicing",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:backend",
    docsRef: "docs/02_FEATURES/features/invoicing-create.md",
    codeRef: "src/lib/modules/definitions.ts",
    dependencies: [
      { componentId: "store-postgresql", type: "HARD" },
      { componentId: "module-contacts", type: "SOFT" },
      { componentId: "module-products", type: "SOFT" },
    ],
    criticalPaths: ["path-fiscalization"],
  },
  {
    componentId: "module-e-invoicing",
    type: "MODULE",
    name: "E-Invoicing",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:backend",
    docsRef: "docs/02_FEATURES/features/e-invoicing-create.md",
    codeRef: "src/lib/modules/definitions.ts",
    dependencies: [
      { componentId: "module-invoicing", type: "HARD" },
      { componentId: "store-r2", type: "SOFT" },
    ],
    criticalPaths: [],
  },
  {
    componentId: "module-fiscalization",
    type: "MODULE",
    name: "Fiscalization",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:rtl",
    docsRef: "docs/02_FEATURES/features/fiscal-fiscalize.md",
    codeRef: "src/lib/modules/definitions.ts",
    dependencies: [
      { componentId: "integration-fina-cis", type: "HARD" },
      { componentId: "lib-fiscal", type: "HARD" },
    ],
    criticalPaths: ["path-fiscalization"],
  },
  {
    componentId: "module-contacts",
    type: "MODULE",
    name: "Contacts",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:backend",
    docsRef: "docs/02_FEATURES/features/contacts-create.md",
    codeRef: "src/lib/modules/definitions.ts",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
  },
  {
    componentId: "module-products",
    type: "MODULE",
    name: "Products",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:backend",
    docsRef: "docs/02_FEATURES/features/products-create.md",
    codeRef: "src/lib/modules/definitions.ts",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
  },
  {
    componentId: "module-expenses",
    type: "MODULE",
    name: "Expenses",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:backend",
    docsRef: "docs/02_FEATURES/features/expenses-create.md",
    codeRef: "src/lib/modules/definitions.ts",
    dependencies: [
      { componentId: "store-postgresql", type: "HARD" },
      { componentId: "store-r2", type: "SOFT" },
    ],
    criticalPaths: [],
  },
  {
    componentId: "module-banking",
    type: "MODULE",
    name: "Banking",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:backend",
    docsRef: "docs/02_FEATURES/features/banking-accounts.md",
    codeRef: "src/lib/modules/definitions.ts",
    dependencies: [
      { componentId: "integration-gocardless", type: "HARD" },
      { componentId: "store-postgresql", type: "HARD" },
    ],
    criticalPaths: [],
  },
  {
    componentId: "module-reconciliation",
    type: "MODULE",
    name: "Reconciliation",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:backend",
    docsRef: "docs/02_FEATURES/features/banking-reconciliation.md",
    codeRef: "src/lib/modules/definitions.ts",
    dependencies: [{ componentId: "module-banking", type: "HARD" }],
    criticalPaths: [],
  },
  {
    componentId: "module-reports-basic",
    type: "MODULE",
    name: "Basic Reports",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: "docs/02_FEATURES/features/reports-kpr.md",
    codeRef: "src/lib/modules/definitions.ts",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
  },
  {
    componentId: "module-reports-advanced",
    type: "MODULE",
    name: "Advanced Reports",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: "docs/02_FEATURES/features/reports-vat.md",
    codeRef: "src/lib/modules/definitions.ts",
    dependencies: [{ componentId: "module-reports-basic", type: "HARD" }],
    criticalPaths: [],
  },
  {
    componentId: "module-pausalni",
    type: "MODULE",
    name: "Paušalni",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:rtl",
    docsRef: "docs/02_FEATURES/features/pausalni-dashboard.md",
    codeRef: "src/lib/modules/definitions.ts",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
  },
  {
    componentId: "module-vat",
    type: "MODULE",
    name: "VAT",
    status: "BETA",
    criticality: "CRITICAL",
    owner: "team:rtl",
    docsRef: null,
    codeRef: "src/lib/modules/definitions.ts",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
  },
  {
    componentId: "module-corporate-tax",
    type: "MODULE",
    name: "Corporate Tax",
    status: "DEPRECATED",
    criticality: "LOW",
    owner: null,
    docsRef: null,
    codeRef: "src/lib/modules/definitions.ts",
    dependencies: [],
    criticalPaths: [],
  },
  {
    componentId: "module-pos",
    type: "MODULE",
    name: "POS",
    status: "BETA",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/lib/modules/definitions.ts",
    dependencies: [{ componentId: "integration-stripe", type: "HARD" }],
    criticalPaths: [],
  },
  {
    componentId: "module-documents",
    type: "MODULE",
    name: "Documents",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/lib/modules/definitions.ts",
    dependencies: [{ componentId: "store-r2", type: "HARD" }],
    criticalPaths: [],
  },
  {
    componentId: "module-ai-assistant",
    type: "MODULE",
    name: "AI Assistant",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:ai",
    docsRef: "docs/03_ARCHITECTURE/AI_ASSISTANT.md",
    codeRef: "src/lib/modules/definitions.ts",
    dependencies: [
      { componentId: "lib-assistant", type: "HARD" },
      { componentId: "lib-regulatory-truth", type: "DATA" },
    ],
    criticalPaths: [],
  },
]

// =============================================================================
// API ROUTE GROUPS
// =============================================================================

export const ROUTE_GROUP_COMPONENTS: SystemComponent[] = [
  {
    componentId: "route-group-admin",
    type: "ROUTE_GROUP",
    name: "Admin API",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/admin/",
    dependencies: [
      { componentId: "lib-auth", type: "SECURITY" },
      { componentId: "store-postgresql", type: "HARD" },
    ],
    criticalPaths: [],
    metadata: { endpointCount: 25 },
  },
  {
    componentId: "route-group-ai",
    type: "ROUTE_GROUP",
    name: "AI API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/app/api/ai/",
    dependencies: [{ componentId: "lib-assistant", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 4 },
  },
  {
    componentId: "route-group-assistant",
    type: "ROUTE_GROUP",
    name: "Assistant API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/app/api/assistant/",
    dependencies: [{ componentId: "lib-assistant", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 5 },
  },
  {
    componentId: "route-group-auth",
    type: "ROUTE_GROUP",
    name: "Auth API",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/auth/",
    dependencies: [
      { componentId: "lib-auth", type: "HARD" },
      { componentId: "store-postgresql", type: "HARD" },
    ],
    criticalPaths: ["path-authentication"],
    metadata: { endpointCount: 6 },
  },
  {
    componentId: "route-group-bank",
    type: "ROUTE_GROUP",
    name: "Bank Connection API",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/bank/",
    dependencies: [{ componentId: "integration-gocardless", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 3 },
  },
  {
    componentId: "route-group-banking",
    type: "ROUTE_GROUP",
    name: "Banking API",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/banking/",
    dependencies: [
      { componentId: "module-banking", type: "HARD" },
      { componentId: "store-postgresql", type: "HARD" },
    ],
    criticalPaths: [],
    metadata: { endpointCount: 7 },
  },
  {
    componentId: "route-group-billing",
    type: "ROUTE_GROUP",
    name: "Billing API",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/billing/",
    dependencies: [
      { componentId: "lib-billing", type: "HARD" },
      { componentId: "integration-stripe", type: "HARD" },
    ],
    criticalPaths: ["path-billing"],
    metadata: { endpointCount: 3 },
  },
  {
    componentId: "route-group-cache",
    type: "ROUTE_GROUP",
    name: "Cache API",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/cache/",
    dependencies: [{ componentId: "lib-cache", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 1 },
  },
  {
    componentId: "route-group-capabilities",
    type: "ROUTE_GROUP",
    name: "Capabilities API",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/capabilities/",
    dependencies: [{ componentId: "lib-modules", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 1 },
  },
  {
    componentId: "route-group-compliance",
    type: "ROUTE_GROUP",
    name: "Compliance API",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:rtl",
    docsRef: null,
    codeRef: "src/app/api/compliance/",
    dependencies: [],
    criticalPaths: [],
    metadata: { endpointCount: 1 },
  },
  {
    componentId: "route-group-cron",
    type: "ROUTE_GROUP",
    name: "Cron API",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/cron/",
    dependencies: [],
    criticalPaths: [],
    metadata: { endpointCount: 12 },
  },
  {
    componentId: "route-group-deadlines",
    type: "ROUTE_GROUP",
    name: "Deadlines API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/deadlines/",
    dependencies: [],
    criticalPaths: [],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-e-invoices",
    type: "ROUTE_GROUP",
    name: "E-Invoices API",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/e-invoices/",
    dependencies: [{ componentId: "module-e-invoicing", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-email",
    type: "ROUTE_GROUP",
    name: "Email API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/email/",
    dependencies: [{ componentId: "integration-resend", type: "SOFT" }],
    criticalPaths: [],
    metadata: { endpointCount: 5 },
  },
  {
    componentId: "route-group-exports",
    type: "ROUTE_GROUP",
    name: "Exports API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/exports/",
    dependencies: [],
    criticalPaths: [],
    metadata: { endpointCount: 4 },
  },
  {
    componentId: "route-group-guidance",
    type: "ROUTE_GROUP",
    name: "Guidance API",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/guidance/",
    dependencies: [{ componentId: "lib-guidance", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 3 },
  },
  {
    componentId: "route-group-health",
    type: "ROUTE_GROUP",
    name: "Health API",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/health/",
    dependencies: [],
    criticalPaths: [],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-import",
    type: "ROUTE_GROUP",
    name: "Import API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/import/",
    dependencies: [],
    criticalPaths: [],
    metadata: { endpointCount: 7 },
  },
  {
    componentId: "route-group-invoices",
    type: "ROUTE_GROUP",
    name: "Invoices API",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/invoices/",
    dependencies: [{ componentId: "module-invoicing", type: "HARD" }],
    criticalPaths: ["path-fiscalization"],
    metadata: { endpointCount: 1 },
  },
  {
    componentId: "route-group-knowledge-hub",
    type: "ROUTE_GROUP",
    name: "Knowledge Hub API",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/knowledge-hub/",
    dependencies: [],
    criticalPaths: [],
    metadata: { endpointCount: 1 },
  },
  {
    componentId: "route-group-metrics",
    type: "ROUTE_GROUP",
    name: "Metrics API",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/metrics/",
    dependencies: [],
    criticalPaths: [],
    metadata: { endpointCount: 1 },
  },
  {
    componentId: "route-group-news",
    type: "ROUTE_GROUP",
    name: "News API",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/news/",
    dependencies: [],
    criticalPaths: [],
    metadata: { endpointCount: 5 },
  },
  {
    componentId: "route-group-notifications",
    type: "ROUTE_GROUP",
    name: "Notifications API",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/notifications/",
    dependencies: [],
    criticalPaths: [],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-oib",
    type: "ROUTE_GROUP",
    name: "OIB API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/oib/",
    dependencies: [],
    criticalPaths: [],
    metadata: { endpointCount: 1 },
  },
  {
    componentId: "route-group-pausalni",
    type: "ROUTE_GROUP",
    name: "Pausalni API",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:rtl",
    docsRef: null,
    codeRef: "src/app/api/pausalni/",
    dependencies: [{ componentId: "module-pausalni", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 12 },
  },
  {
    componentId: "route-group-products",
    type: "ROUTE_GROUP",
    name: "Products API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/products/",
    dependencies: [{ componentId: "module-products", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 1 },
  },
  {
    componentId: "route-group-receipts",
    type: "ROUTE_GROUP",
    name: "Receipts API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/receipts/",
    dependencies: [],
    criticalPaths: [],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-regulatory",
    type: "ROUTE_GROUP",
    name: "Regulatory API",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/app/api/regulatory/",
    dependencies: [{ componentId: "lib-regulatory-truth", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 4 },
  },
  {
    componentId: "route-group-reports",
    type: "ROUTE_GROUP",
    name: "Reports API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/reports/",
    dependencies: [{ componentId: "module-reports-basic", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 5 },
  },
  {
    componentId: "route-group-rules",
    type: "ROUTE_GROUP",
    name: "Rules API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/app/api/rules/",
    dependencies: [{ componentId: "lib-regulatory-truth", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-sandbox",
    type: "ROUTE_GROUP",
    name: "Sandbox API",
    status: "BETA",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/sandbox/",
    dependencies: [],
    criticalPaths: [],
    metadata: { endpointCount: 1 },
  },
  {
    componentId: "route-group-staff",
    type: "ROUTE_GROUP",
    name: "Staff API",
    status: "BETA",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: "docs/02_FEATURES/features/staff-portal.md",
    codeRef: "src/app/api/staff/",
    dependencies: [],
    criticalPaths: [],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-status",
    type: "ROUTE_GROUP",
    name: "Status API",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/status/",
    dependencies: [],
    criticalPaths: [],
    metadata: { endpointCount: 1 },
  },
  {
    componentId: "route-group-support",
    type: "ROUTE_GROUP",
    name: "Support API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/support/",
    dependencies: [],
    criticalPaths: [],
    metadata: { endpointCount: 4 },
  },
  {
    componentId: "route-group-terminal",
    type: "ROUTE_GROUP",
    name: "Terminal API",
    status: "BETA",
    criticality: "HIGH",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/terminal/",
    dependencies: [{ componentId: "integration-stripe", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 3 },
  },
  {
    componentId: "route-group-webauthn",
    type: "ROUTE_GROUP",
    name: "WebAuthn API",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/webauthn/",
    dependencies: [{ componentId: "lib-auth", type: "HARD" }],
    criticalPaths: ["path-authentication"],
    metadata: { endpointCount: 6 },
  },
  {
    componentId: "route-group-webhooks",
    type: "ROUTE_GROUP",
    name: "Webhooks API",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/webhooks/",
    dependencies: [{ componentId: "integration-stripe", type: "HARD" }],
    criticalPaths: ["path-billing"],
    metadata: { endpointCount: 1 },
  },
  {
    componentId: "route-group-accounting-periods",
    type: "ROUTE_GROUP",
    name: "Accounting Periods API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/accounting-periods/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-audit",
    type: "ROUTE_GROUP",
    name: "Audit API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/audit/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 1 },
  },
  {
    componentId: "route-group-backup",
    type: "ROUTE_GROUP",
    name: "Backup API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/backup/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-cash",
    type: "ROUTE_GROUP",
    name: "Cash API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/cash/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 3 },
  },
  {
    componentId: "route-group-contacts",
    type: "ROUTE_GROUP",
    name: "Contacts API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/contacts/",
    dependencies: [{ componentId: "module-contacts", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-contracts",
    type: "ROUTE_GROUP",
    name: "Contracts API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/contracts/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-experiments",
    type: "ROUTE_GROUP",
    name: "Experiments API",
    status: "BETA",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/experiments/",
    dependencies: [],
    criticalPaths: [],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-feature-flags",
    type: "ROUTE_GROUP",
    name: "Feature Flags API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/feature-flags/",
    dependencies: [],
    criticalPaths: [],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-fiscal",
    type: "ROUTE_GROUP",
    name: "Fiscal API",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:rtl",
    docsRef: null,
    codeRef: "src/app/api/fiscal/",
    dependencies: [
      { componentId: "lib-fiscal", type: "HARD" },
      { componentId: "integration-fina-cis", type: "HARD" },
    ],
    criticalPaths: ["path-fiscalization"],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-invitations",
    type: "ROUTE_GROUP",
    name: "Invitations API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/invitations/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-joppd",
    type: "ROUTE_GROUP",
    name: "JOPPD API",
    status: "BETA",
    criticality: "HIGH",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/joppd/",
    dependencies: [
      { componentId: "store-postgresql", type: "HARD" },
      { componentId: "lib-joppd", type: "HARD" },
    ],
    criticalPaths: [],
    metadata: { endpointCount: 1 },
  },
  {
    componentId: "route-group-newsletter",
    type: "ROUTE_GROUP",
    name: "Newsletter API",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/newsletter/",
    dependencies: [{ componentId: "integration-resend", type: "SOFT" }],
    criticalPaths: [],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-payroll",
    type: "ROUTE_GROUP",
    name: "Payroll API",
    status: "BETA",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/payroll/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 3 },
  },
  {
    componentId: "route-group-people",
    type: "ROUTE_GROUP",
    name: "People API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/people/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-procurement",
    type: "ROUTE_GROUP",
    name: "Procurement API",
    status: "BETA",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/procurement/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-reporting-status",
    type: "ROUTE_GROUP",
    name: "Reporting Status API",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/reporting-status/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 2 },
  },
  {
    componentId: "route-group-tenancy",
    type: "ROUTE_GROUP",
    name: "Tenancy API",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/tenancy/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { endpointCount: 1 },
  },
]

// =============================================================================
// WORKERS
// =============================================================================

export const WORKER_COMPONENTS: SystemComponent[] = [
  {
    componentId: "worker-orchestrator",
    type: "WORKER",
    name: "RTL Orchestrator Worker",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:ai",
    docsRef: "docs/01_ARCHITECTURE/REGULATORY_TRUTH_LAYER.md",
    codeRef: "src/lib/regulatory-truth/workers/orchestrator.worker.ts",
    dependencies: [
      { componentId: "store-redis", type: "HARD" },
      { componentId: "lib-regulatory-truth", type: "HARD" },
    ],
    criticalPaths: ["path-rtl-pipeline"],
  },
  {
    componentId: "worker-sentinel",
    type: "WORKER",
    name: "RTL Sentinel Worker",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:ai",
    docsRef: "docs/01_ARCHITECTURE/REGULATORY_TRUTH_LAYER.md",
    codeRef: "src/lib/regulatory-truth/workers/sentinel.worker.ts",
    dependencies: [
      { componentId: "store-redis", type: "HARD" },
      { componentId: "queue-sentinel", type: "HARD" },
    ],
    criticalPaths: ["path-rtl-pipeline"],
  },
  {
    componentId: "worker-extractor",
    type: "WORKER",
    name: "RTL Extractor Worker",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:ai",
    docsRef: "docs/01_ARCHITECTURE/REGULATORY_TRUTH_LAYER.md",
    codeRef: "src/lib/regulatory-truth/workers/extractor.worker.ts",
    dependencies: [
      { componentId: "store-redis", type: "HARD" },
      { componentId: "queue-extract", type: "HARD" },
      { componentId: "integration-ollama", type: "HARD" },
    ],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: { replicas: 2, concurrency: 2 },
  },
  {
    componentId: "worker-ocr",
    type: "WORKER",
    name: "RTL OCR Worker",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: "docs/01_ARCHITECTURE/REGULATORY_TRUTH_LAYER.md",
    codeRef: "src/lib/regulatory-truth/workers/ocr.worker.ts",
    dependencies: [
      { componentId: "store-redis", type: "HARD" },
      { componentId: "queue-ocr", type: "HARD" },
      { componentId: "integration-ollama", type: "HARD" },
    ],
    criticalPaths: ["path-rtl-pipeline"],
  },
  {
    componentId: "worker-composer",
    type: "WORKER",
    name: "RTL Composer Worker",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:ai",
    docsRef: "docs/01_ARCHITECTURE/REGULATORY_TRUTH_LAYER.md",
    codeRef: "src/lib/regulatory-truth/workers/composer.worker.ts",
    dependencies: [
      { componentId: "store-redis", type: "HARD" },
      { componentId: "queue-compose", type: "HARD" },
    ],
    criticalPaths: ["path-rtl-pipeline"],
  },
  {
    componentId: "worker-reviewer",
    type: "WORKER",
    name: "RTL Reviewer Worker",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: "docs/01_ARCHITECTURE/REGULATORY_TRUTH_LAYER.md",
    codeRef: "src/lib/regulatory-truth/workers/reviewer.worker.ts",
    dependencies: [
      { componentId: "store-redis", type: "HARD" },
      { componentId: "queue-review", type: "HARD" },
    ],
    criticalPaths: ["path-rtl-pipeline"],
  },
  {
    componentId: "worker-scheduler",
    type: "WORKER",
    name: "RTL Scheduler Service",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: "docs/01_ARCHITECTURE/REGULATORY_TRUTH_LAYER.md",
    codeRef: "src/lib/regulatory-truth/workers/scheduler.service.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: ["path-rtl-pipeline"],
  },
  {
    componentId: "worker-releaser",
    type: "WORKER",
    name: "RTL Releaser Worker",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:ai",
    docsRef: "docs/01_ARCHITECTURE/REGULATORY_TRUTH_LAYER.md",
    codeRef: "src/lib/regulatory-truth/workers/releaser.worker.ts",
    dependencies: [
      { componentId: "store-redis", type: "HARD" },
      { componentId: "queue-release", type: "HARD" },
    ],
    criticalPaths: ["path-rtl-pipeline"],
  },
  {
    componentId: "worker-arbiter",
    type: "WORKER",
    name: "RTL Arbiter Worker",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: "docs/01_ARCHITECTURE/REGULATORY_TRUTH_LAYER.md",
    codeRef: "src/lib/regulatory-truth/workers/arbiter.worker.ts",
    dependencies: [
      { componentId: "store-redis", type: "HARD" },
      { componentId: "queue-arbiter", type: "HARD" },
    ],
    criticalPaths: ["path-rtl-pipeline"],
  },
  {
    componentId: "worker-continuous-drainer",
    type: "WORKER",
    name: "RTL Continuous Drainer",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: "docs/01_ARCHITECTURE/REGULATORY_TRUTH_LAYER.md",
    codeRef: "src/lib/regulatory-truth/workers/continuous-drainer.worker.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: ["path-rtl-pipeline"],
  },
  {
    componentId: "worker-content-sync",
    type: "WORKER",
    name: "RTL Content Sync Worker",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: "docs/01_ARCHITECTURE/REGULATORY_TRUTH_LAYER.md",
    codeRef: "src/lib/regulatory-truth/workers/content-sync.worker.ts",
    dependencies: [
      { componentId: "store-redis", type: "HARD" },
      { componentId: "queue-content-sync", type: "HARD" },
    ],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: { purpose: "MDX content patching for regulatory rules" },
  },
  {
    componentId: "worker-article",
    type: "WORKER",
    name: "RTL Article Worker",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: "docs/01_ARCHITECTURE/REGULATORY_TRUTH_LAYER.md",
    codeRef: "src/lib/regulatory-truth/workers/article.worker.ts",
    dependencies: [
      { componentId: "store-redis", type: "HARD" },
      { componentId: "queue-article", type: "HARD" },
      { componentId: "integration-ollama", type: "HARD" },
    ],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: { purpose: "Article generation from regulatory rules" },
  },
  {
    componentId: "worker-embedding",
    type: "WORKER",
    name: "RTL Embedding Worker",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: "docs/01_ARCHITECTURE/REGULATORY_TRUTH_LAYER.md",
    codeRef: "src/lib/regulatory-truth/workers/embedding.worker.ts",
    dependencies: [
      { componentId: "store-redis", type: "HARD" },
      { componentId: "queue-embedding", type: "HARD" },
    ],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: { purpose: "Generate embeddings for published regulatory rules" },
  },
  {
    componentId: "worker-einvoice-inbound",
    type: "WORKER",
    name: "E-Invoice Inbound Poller",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:einvoice",
    docsRef: null,
    codeRef: "src/lib/e-invoice/workers/eposlovanje-inbound-poller.worker.ts",
    dependencies: [
      { componentId: "store-postgresql", type: "HARD" },
      { componentId: "integration-einvoice", type: "HARD" },
    ],
    criticalPaths: [],
    metadata: { purpose: "Poll ePoslovanje for incoming e-invoices" },
  },
]

// =============================================================================
// JOBS (Cron)
// =============================================================================

export const JOB_COMPONENTS: SystemComponent[] = [
  {
    componentId: "job-fiscal-processor",
    type: "JOB",
    name: "Fiscal Processor Cron",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:rtl",
    docsRef: null,
    codeRef: "src/app/api/cron/fiscal-processor/route.ts",
    dependencies: [
      { componentId: "lib-fiscal", type: "HARD" },
      { componentId: "integration-fina-cis", type: "HARD" },
    ],
    criticalPaths: ["path-fiscalization"],
  },
  {
    componentId: "job-checklist-digest",
    type: "JOB",
    name: "Checklist Digest Cron",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/cron/checklist-digest/route.ts",
    dependencies: [{ componentId: "lib-guidance", type: "SOFT" }],
    criticalPaths: [],
  },
  {
    componentId: "job-email-sync",
    type: "JOB",
    name: "Email Sync Cron",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/cron/email-sync/route.ts",
    dependencies: [],
    criticalPaths: [],
  },
  {
    componentId: "job-bank-sync",
    type: "JOB",
    name: "Bank Sync Cron",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/cron/bank-sync/route.ts",
    dependencies: [{ componentId: "integration-gocardless", type: "HARD" }],
    criticalPaths: [],
  },
  {
    componentId: "job-deadline-reminders",
    type: "JOB",
    name: "Deadline Reminders Cron",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/cron/deadline-reminders/route.ts",
    dependencies: [{ componentId: "integration-resend", type: "SOFT" }],
    criticalPaths: [],
  },
  {
    componentId: "job-fiscal-retry",
    type: "JOB",
    name: "Fiscal Retry Cron",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:rtl",
    docsRef: null,
    codeRef: "src/app/api/cron/fiscal-retry/route.ts",
    dependencies: [
      { componentId: "lib-fiscal", type: "HARD" },
      { componentId: "integration-fina-cis", type: "HARD" },
    ],
    criticalPaths: ["path-fiscalization"],
  },
  {
    componentId: "job-weekly-digest",
    type: "JOB",
    name: "Weekly Digest Cron",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/cron/weekly-digest/route.ts",
    dependencies: [{ componentId: "integration-resend", type: "SOFT" }],
    criticalPaths: [],
  },
  {
    componentId: "job-news-review",
    type: "JOB",
    name: "News Review Cron",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/cron/news/review/route.ts",
    dependencies: [],
    criticalPaths: [],
  },
  {
    componentId: "job-news-fetch-classify",
    type: "JOB",
    name: "News Fetch & Classify Cron",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/cron/news/fetch-classify/route.ts",
    dependencies: [],
    criticalPaths: [],
  },
  {
    componentId: "job-news-publish",
    type: "JOB",
    name: "News Publish Cron",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/cron/news/publish/route.ts",
    dependencies: [],
    criticalPaths: [],
  },
  {
    componentId: "job-certificate-check",
    type: "JOB",
    name: "Certificate Check Cron",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:rtl",
    docsRef: null,
    codeRef: "src/app/api/cron/certificate-check/route.ts",
    dependencies: [{ componentId: "lib-fiscal", type: "HARD" }],
    criticalPaths: ["path-fiscalization"],
  },
  {
    componentId: "job-system-status-cleanup",
    type: "JOB",
    name: "System Status Cleanup Cron",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/cron/system-status-cleanup/route.ts",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { schedule: "daily", purpose: "Cleanup old system status events" },
  },
  {
    componentId: "job-ai-quality-digest",
    type: "JOB",
    name: "AI Quality Digest Cron",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/app/api/cron/ai-quality-digest/route.ts",
    dependencies: [],
    criticalPaths: [],
    metadata: { schedule: "daily", purpose: "Generate AI quality metrics digest" },
  },
  {
    componentId: "job-cleanup-uploads",
    type: "JOB",
    name: "Cleanup Uploads Cron",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/cron/cleanup-uploads/route.ts",
    dependencies: [{ componentId: "store-r2", type: "SOFT" }],
    criticalPaths: [],
    metadata: { schedule: "daily", purpose: "Remove orphaned upload files" },
  },
  {
    componentId: "job-news-stale-check",
    type: "JOB",
    name: "News Stale Check Cron",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/cron/news/stale-check/route.ts",
    dependencies: [],
    criticalPaths: [],
    metadata: { schedule: "daily", purpose: "Check for stale news articles" },
  },
  {
    componentId: "job-newsletter-send",
    type: "JOB",
    name: "Newsletter Send Cron",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/cron/newsletter-send/route.ts",
    dependencies: [{ componentId: "integration-resend", type: "HARD" }],
    criticalPaths: [],
    metadata: { schedule: "weekly", purpose: "Send scheduled newsletter emails" },
  },
  {
    componentId: "job-recurring-expenses",
    type: "JOB",
    name: "Recurring Expenses Cron",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/app/api/cron/recurring-expenses/route.ts",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { schedule: "daily", purpose: "Generate recurring expense entries" },
  },
  {
    componentId: "job-rtl-staleness",
    type: "JOB",
    name: "RTL Staleness Check Cron",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/app/api/cron/rtl-staleness/route.ts",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: { schedule: "daily", purpose: "Check regulatory content staleness" },
  },
  {
    componentId: "job-support-escalation",
    type: "JOB",
    name: "Support Escalation Cron",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/api/cron/support-escalation/route.ts",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { schedule: "hourly", purpose: "Escalate unresolved support tickets" },
  },
]

// =============================================================================
// QUEUES
// =============================================================================

export const QUEUE_COMPONENTS: SystemComponent[] = [
  {
    componentId: "queue-sentinel",
    type: "QUEUE",
    name: "Sentinel Queue",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/lib/regulatory-truth/workers/queues.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: { rateLimiter: { max: 5, duration: 60000 } },
  },
  {
    componentId: "queue-extract",
    type: "QUEUE",
    name: "Extract Queue",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/lib/regulatory-truth/workers/queues.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: { rateLimiter: { max: 10, duration: 60000 } },
  },
  {
    componentId: "queue-ocr",
    type: "QUEUE",
    name: "OCR Queue",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/lib/regulatory-truth/workers/queues.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: { rateLimiter: { max: 2, duration: 60000 } },
  },
  {
    componentId: "queue-compose",
    type: "QUEUE",
    name: "Compose Queue",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/lib/regulatory-truth/workers/queues.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: { rateLimiter: { max: 5, duration: 60000 } },
  },
  {
    componentId: "queue-review",
    type: "QUEUE",
    name: "Review Queue",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/lib/regulatory-truth/workers/queues.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: { rateLimiter: { max: 5, duration: 60000 } },
  },
  {
    componentId: "queue-arbiter",
    type: "QUEUE",
    name: "Arbiter Queue",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/lib/regulatory-truth/workers/queues.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: { rateLimiter: { max: 3, duration: 60000 } },
  },
  {
    componentId: "queue-release",
    type: "QUEUE",
    name: "Release Queue",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/lib/regulatory-truth/workers/queues.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: { rateLimiter: { max: 2, duration: 60000 } },
  },
  {
    componentId: "queue-consolidator",
    type: "QUEUE",
    name: "Consolidator Queue",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/lib/regulatory-truth/workers/queues.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: [],
    metadata: { rateLimiter: { max: 1, duration: 300000 } },
  },
  {
    componentId: "queue-scheduled",
    type: "QUEUE",
    name: "Scheduled Queue",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/lib/regulatory-truth/workers/queues.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: [],
  },
  {
    componentId: "queue-deadletter",
    type: "QUEUE",
    name: "Deadletter Queue",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/regulatory-truth/workers/queues.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: [],
  },
  {
    componentId: "queue-content-sync",
    type: "QUEUE",
    name: "Content Sync Queue",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/lib/regulatory-truth/workers/queues.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: { rateLimiter: { max: 2, duration: 60000 }, purpose: "MDX patching jobs" },
  },
  {
    componentId: "queue-system-status",
    type: "QUEUE",
    name: "System Status Queue",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/regulatory-truth/workers/queues.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: [],
    metadata: { purpose: "Human control layer status processing" },
  },
  {
    componentId: "queue-article",
    type: "QUEUE",
    name: "Article Queue",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/lib/regulatory-truth/workers/queues.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: { rateLimiter: { max: 2, duration: 60000 }, purpose: "Article generation jobs" },
  },
  {
    componentId: "queue-backup",
    type: "QUEUE",
    name: "Backup Queue",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/regulatory-truth/workers/queues.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: [],
    metadata: { rateLimiter: { max: 2, duration: 60000 }, purpose: "Company data backup jobs" },
  },
  {
    componentId: "queue-embedding",
    type: "QUEUE",
    name: "Embedding Queue",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/lib/regulatory-truth/workers/queues.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: { rateLimiter: { max: 10, duration: 60000 }, purpose: "Rule embedding generation" },
  },
  {
    componentId: "queue-evidence-embedding",
    type: "QUEUE",
    name: "Evidence Embedding Queue",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/lib/regulatory-truth/workers/queues.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: {
      rateLimiter: { max: 5, duration: 60000 },
      purpose: "Evidence embedding for semantic duplicate detection",
    },
  },
  {
    componentId: "queue-outbox",
    type: "QUEUE",
    name: "Outbox Queue",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/outbox/outbox-worker.ts",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: [],
    metadata: { purpose: "Scheduled polling jobs for outbox pattern" },
  },
]

// =============================================================================
// STORES
// =============================================================================

export const STORE_COMPONENTS: SystemComponent[] = [
  {
    componentId: "store-postgresql",
    type: "STORE",
    name: "PostgreSQL Database",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:platform",
    docsRef: null,
    codeRef: "prisma/schema.prisma",
    dependencies: [],
    dependents: [
      "ui-portal-app",
      "ui-portal-staff",
      "ui-portal-admin",
      "module-invoicing",
      "module-contacts",
      "module-products",
      "module-expenses",
      "module-banking",
      "module-pausalni",
      "module-vat",
      "lib-regulatory-truth",
      "route-group-auth",
    ],
    criticalPaths: ["path-authentication", "path-fiscalization", "path-billing"],
    metadata: { modelCount: 82 },
  },
  {
    componentId: "store-redis",
    type: "STORE",
    name: "Redis Cache & Queue Backend",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:platform",
    docsRef: null,
    codeRef: "docker-compose.workers.yml",
    dependencies: [],
    dependents: [
      "worker-orchestrator",
      "worker-sentinel",
      "worker-extractor",
      "worker-ocr",
      "worker-composer",
      "worker-reviewer",
      "worker-releaser",
      "worker-arbiter",
      "worker-scheduler",
      "worker-continuous-drainer",
      "queue-sentinel",
      "queue-extract",
      "queue-ocr",
      "queue-compose",
      "queue-review",
      "queue-arbiter",
      "queue-release",
      "queue-consolidator",
      "queue-scheduled",
      "queue-deadletter",
      "lib-cache",
    ],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: { maxMemory: "512mb" },
  },
  {
    componentId: "store-r2",
    type: "STORE",
    name: "Cloudflare R2 Object Storage",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/r2-client.ts",
    dependencies: [],
    dependents: ["module-e-invoicing", "module-expenses", "module-documents"],
    criticalPaths: [],
    metadata: { bucket: "fiskai-documents" },
  },
]

// =============================================================================
// INTEGRATIONS
// =============================================================================

export const INTEGRATION_COMPONENTS: SystemComponent[] = [
  {
    componentId: "integration-resend",
    type: "INTEGRATION",
    name: "Resend Email Service",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/email/",
    dependencies: [],
    dependents: ["job-deadline-reminders", "job-weekly-digest", "route-group-email"],
    criticalPaths: [],
  },
  {
    componentId: "integration-stripe",
    type: "INTEGRATION",
    name: "Stripe Payment & Terminal",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/stripe/",
    dependencies: [],
    dependents: [
      "module-pos",
      "route-group-billing",
      "route-group-terminal",
      "route-group-webhooks",
      "lib-billing",
    ],
    criticalPaths: ["path-billing"],
    metadata: { features: ["billing", "terminal", "webhooks"] },
  },
  {
    componentId: "integration-gocardless",
    type: "INTEGRATION",
    name: "GoCardless Open Banking",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/lib/bank-sync/providers/gocardless.ts",
    dependencies: [],
    dependents: ["module-banking", "route-group-bank", "job-bank-sync"],
    criticalPaths: [],
  },
  {
    componentId: "integration-fina-cis",
    type: "INTEGRATION",
    name: "FINA CIS Fiscalization",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:rtl",
    docsRef: "docs/FISCALIZATION.md",
    codeRef: "src/lib/fiscal/porezna-client.ts",
    dependencies: [],
    dependents: ["module-fiscalization", "lib-fiscal", "job-fiscal-processor", "job-fiscal-retry"],
    criticalPaths: ["path-fiscalization"],
  },
  {
    componentId: "integration-ollama",
    type: "INTEGRATION",
    name: "Ollama LLM Service",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/lib/article-agent/llm/ollama-client.ts",
    dependencies: [],
    dependents: ["worker-extractor", "worker-ocr", "worker-composer", "worker-arbiter"],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: { models: ["extraction", "vision"] },
  },
  {
    componentId: "integration-turnstile",
    type: "INTEGRATION",
    name: "Cloudflare Turnstile",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/turnstile.ts",
    dependencies: [],
    dependents: [],
    criticalPaths: [],
  },
  {
    componentId: "integration-microsoft-entra",
    type: "INTEGRATION",
    name: "Microsoft OAuth (Email Sync)",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/lib/email-sync/providers/microsoft.ts",
    dependencies: [],
    dependents: [],
    criticalPaths: [],
    metadata: { purpose: "Microsoft OAuth for email inbox sync" },
  },
  {
    componentId: "integration-einvoice",
    type: "INTEGRATION",
    name: "E-Invoice Service (eRačun)",
    status: "PLANNED",
    criticality: "HIGH",
    owner: "team:rtl",
    docsRef: null,
    codeRef: "src/lib/e-invoice/index.ts",
    dependencies: [],
    dependents: ["module-e-invoicing"],
    criticalPaths: ["path-e-invoicing"],
    metadata: { purpose: "Croatian e-invoicing compliance" },
  },
  {
    componentId: "integration-ollama",
    type: "INTEGRATION",
    name: "Ollama LLM",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/lib/ai/ollama-client.ts",
    dependencies: [],
    dependents: [],
    criticalPaths: [],
    metadata: {
      purpose: "AI-powered extraction, OCR, and assistant (local and cloud Ollama instances)",
    },
  },
  {
    componentId: "integration-posthog",
    type: "INTEGRATION",
    name: "PostHog Analytics",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/analytics.ts",
    dependencies: [],
    dependents: [],
    criticalPaths: [],
    metadata: { purpose: "Product analytics and event tracking" },
  },
  {
    componentId: "integration-sentry",
    type: "INTEGRATION",
    name: "Sentry Error Monitoring",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/app/global-error.tsx",
    dependencies: [],
    dependents: [],
    criticalPaths: [],
    metadata: { purpose: "Error tracking and application monitoring" },
  },
]

// =============================================================================
// LIBRARIES
// =============================================================================

export const LIB_COMPONENTS: SystemComponent[] = [
  {
    componentId: "lib-regulatory-truth",
    type: "LIB",
    name: "Regulatory Truth Layer",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:ai",
    docsRef: "docs/01_ARCHITECTURE/REGULATORY_TRUTH_LAYER.md",
    codeRef: "src/lib/regulatory-truth/",
    dependencies: [
      { componentId: "store-postgresql", type: "HARD" },
      { componentId: "store-redis", type: "HARD" },
      { componentId: "integration-ollama", type: "HARD" },
    ],
    criticalPaths: ["path-rtl-pipeline"],
    metadata: { subdirectories: 22 },
  },
  {
    componentId: "lib-assistant",
    type: "LIB",
    name: "AI Assistant Engine",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:ai",
    docsRef: "docs/03_ARCHITECTURE/AI_ASSISTANT.md",
    codeRef: "src/lib/assistant/",
    dependencies: [{ componentId: "lib-regulatory-truth", type: "DATA" }],
    criticalPaths: [],
    metadata: { files: 90 },
  },
  {
    componentId: "lib-auth",
    type: "LIB",
    name: "Authentication Library",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/auth/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: ["path-authentication"],
  },
  {
    componentId: "lib-guidance",
    type: "LIB",
    name: "Guidance System",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: "docs/product-bible/09-GUIDANCE-SYSTEM.md",
    codeRef: "src/lib/guidance/",
    dependencies: [],
    criticalPaths: [],
    metadata: { files: 9 },
  },
  {
    componentId: "lib-visibility",
    type: "LIB",
    name: "Visibility System",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:platform",
    docsRef: "docs/product-bible/04-ACCESS-CONTROL.md",
    codeRef: "src/lib/visibility/",
    dependencies: [],
    criticalPaths: [],
  },
  {
    componentId: "lib-modules",
    type: "LIB",
    name: "Module System",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/lib/modules/",
    dependencies: [],
    criticalPaths: [],
  },
  {
    componentId: "lib-fiscal",
    type: "LIB",
    name: "Fiscalization Library",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:rtl",
    docsRef: "docs/FISCALIZATION.md",
    codeRef: "src/lib/fiscal/",
    dependencies: [{ componentId: "integration-fina-cis", type: "HARD" }],
    criticalPaths: ["path-fiscalization"],
  },
  {
    componentId: "lib-joppd",
    type: "LIB",
    name: "JOPPD Generator",
    status: "BETA",
    criticality: "HIGH",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/lib/joppd/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { files: 5 },
  },
  {
    componentId: "lib-billing",
    type: "LIB",
    name: "Billing Library",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/billing/",
    dependencies: [{ componentId: "integration-stripe", type: "HARD" }],
    criticalPaths: ["path-billing"],
  },
  {
    componentId: "lib-cache",
    type: "LIB",
    name: "Cache Library",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/cache/",
    dependencies: [{ componentId: "store-redis", type: "HARD" }],
    criticalPaths: [],
  },
  {
    componentId: "lib-middleware",
    type: "LIB",
    name: "Middleware (Subdomain Routing)",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/middleware/",
    dependencies: [],
    criticalPaths: [],
  },
  {
    componentId: "lib-email",
    type: "LIB",
    name: "Email Library",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/email/",
    dependencies: [{ componentId: "integration-resend", type: "HARD" }],
    criticalPaths: [],
  },
  {
    componentId: "lib-banking",
    type: "LIB",
    name: "Banking Library",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/lib/banking/",
    dependencies: [{ componentId: "integration-gocardless", type: "HARD" }],
    criticalPaths: [],
  },
  {
    componentId: "lib-db",
    type: "LIB",
    name: "Database Utilities (Drizzle ORM)",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/db/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
  },
  {
    componentId: "lib-schema",
    type: "LIB",
    name: "Schema Definitions (JSON-LD Generators)",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/schema/",
    dependencies: [],
    criticalPaths: [],
  },
  {
    componentId: "lib-stores",
    type: "LIB",
    name: "Client State Stores (Zustand)",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/stores/",
    dependencies: [],
    criticalPaths: [],
  },
  {
    componentId: "lib-validations",
    type: "LIB",
    name: "Validation Utilities (Zod Schemas)",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/validations/",
    dependencies: [],
    criticalPaths: [],
  },
  {
    componentId: "lib-security",
    type: "LIB",
    name: "Security Utilities (Rate Limiting)",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:security",
    docsRef: null,
    codeRef: "src/lib/security/",
    dependencies: [],
    criticalPaths: ["path-authentication"],
  },
  {
    componentId: "lib-monitoring",
    type: "LIB",
    name: "Monitoring Utilities (System Health)",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/monitoring/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
  },
  {
    componentId: "lib-ai",
    type: "LIB",
    name: "AI Utilities",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/lib/ai/",
    dependencies: [{ componentId: "integration-ollama", type: "HARD" }],
    criticalPaths: [],
    metadata: {
      features: [
        "receipt-extraction",
        "invoice-extraction",
        "ocr",
        "categorization",
        "usage-tracking",
      ],
    },
  },
  {
    componentId: "lib-article-agent",
    type: "LIB",
    name: "Article Generation Agent",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/lib/article-agent/",
    dependencies: [{ componentId: "integration-ollama", type: "HARD" }],
    criticalPaths: [],
    metadata: {
      features: ["claim-extraction", "fact-verification", "draft-generation", "rewriting"],
    },
  },
  {
    componentId: "lib-news",
    type: "LIB",
    name: "News Processing Library",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:ai",
    docsRef: null,
    codeRef: "src/lib/news/",
    dependencies: [],
    criticalPaths: [],
    metadata: {
      features: ["news-fetching", "classification", "review", "publishing", "digest-assembly"],
    },
  },
  {
    componentId: "lib-documents",
    type: "LIB",
    name: "Document Handling Library",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/lib/documents/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { features: ["unified-document-query", "cross-type-search"] },
  },
  {
    componentId: "lib-pdf",
    type: "LIB",
    name: "PDF Generation Library",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/lib/pdf/",
    dependencies: [
      { componentId: "store-postgresql", type: "HARD" },
      { componentId: "lib-fiscal", type: "SOFT" },
    ],
    criticalPaths: [],
    metadata: { features: ["invoice-pdf-generation", "barcode-integration", "fiscal-qr-codes"] },
  },
  {
    componentId: "lib-knowledge-hub",
    type: "LIB",
    name: "Knowledge Hub Library",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/knowledge-hub/",
    dependencies: [],
    criticalPaths: [],
    metadata: {
      features: [
        "mdx-content",
        "guides",
        "comparisons",
        "glossary",
        "hub3-barcodes",
        "oib-validation",
      ],
    },
  },
  {
    componentId: "lib-compliance",
    type: "LIB",
    name: "Compliance Utilities",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:rtl",
    docsRef: null,
    codeRef: "src/lib/compliance/",
    dependencies: [
      { componentId: "store-postgresql", type: "HARD" },
      { componentId: "integration-resend", type: "SOFT" },
    ],
    criticalPaths: ["path-fiscalization"],
    metadata: { purpose: "Certificate monitoring, EN16931 validation, compliance data" },
  },
  {
    componentId: "lib-fiscal-data",
    type: "LIB",
    name: "Fiscal Data Repository",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:rtl",
    docsRef: null,
    codeRef: "src/lib/fiscal-data/",
    dependencies: [],
    criticalPaths: [],
    metadata: {
      purpose: "Croatian fiscal values, tax rates, thresholds, deadlines, payment details",
    },
  },
  {
    componentId: "lib-pausalni",
    type: "LIB",
    name: "Pausalni (Flat-Rate Tax) Logic",
    status: "STABLE",
    criticality: "CRITICAL",
    owner: "team:rtl",
    docsRef: null,
    codeRef: "src/lib/pausalni/",
    dependencies: [{ componentId: "lib-fiscal-data", type: "DATA" }],
    criticalPaths: [],
    metadata: {
      purpose:
        "Contribution calculations, EU vendor detection, obligation generation, payment slips",
    },
  },
  {
    componentId: "lib-reports",
    type: "LIB",
    name: "Report Generation Library",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:finance",
    docsRef: null,
    codeRef: "src/lib/reports/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { purpose: "KPR book, PO-SD reports, accountant exports, PDF/Excel generation" },
  },
  {
    componentId: "lib-e-invoice",
    type: "LIB",
    name: "E-Invoicing Utilities",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:rtl",
    docsRef: null,
    codeRef: "src/lib/e-invoice/",
    dependencies: [],
    criticalPaths: [],
    metadata: { purpose: "UBL generation, ZKI calculation, fiscal provider abstraction" },
  },
  {
    componentId: "lib-deadlines",
    type: "LIB",
    name: "Deadline Tracking Library",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:rtl",
    docsRef: null,
    codeRef: "src/lib/deadlines/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: {
      purpose: "Compliance deadline queries, upcoming deadline tracking by business type",
    },
  },
  {
    componentId: "lib-pos",
    type: "LIB",
    name: "Point of Sale Library",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/lib/pos/",
    dependencies: [{ componentId: "lib-knowledge-hub", type: "SOFT" }],
    criticalPaths: [],
    metadata: { purpose: "HUB-3 payment QR code generation for POS receipts" },
  },
  {
    componentId: "lib-a11y",
    type: "LIB",
    name: "Accessibility Utilities",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/a11y/",
    dependencies: [],
    criticalPaths: [],
    metadata: {
      purpose:
        "WCAG compliance helpers for aria labels, focus management, screen reader announcements",
    },
  },
  {
    componentId: "lib-admin",
    type: "LIB",
    name: "Admin Utilities",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/admin/",
    dependencies: [
      { componentId: "store-postgresql", type: "HARD" },
      { componentId: "lib-auth", type: "SECURITY" },
    ],
    criticalPaths: [],
    metadata: { purpose: "Admin actions for tenant management, module gifting, alerts" },
  },
  {
    componentId: "lib-archive",
    type: "LIB",
    name: "Archive Utilities",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:data",
    docsRef: null,
    codeRef: "src/lib/archive/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: {
      purpose: "Long-term storage and compliance archiving (11-year Croatian retention)",
    },
  },
  {
    componentId: "lib-backup",
    type: "LIB",
    name: "Backup Utilities",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:data",
    docsRef: null,
    codeRef: "src/lib/backup/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { purpose: "Data export and GDPR data portability" },
  },
  {
    componentId: "lib-shortcuts",
    type: "LIB",
    name: "Keyboard Shortcuts",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/shortcuts/",
    dependencies: [],
    criticalPaths: [],
    metadata: { purpose: "Global keyboard shortcut definitions and formatting" },
  },
  {
    componentId: "lib-tutorials",
    type: "LIB",
    name: "Tutorial System",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/tutorials/",
    dependencies: [],
    criticalPaths: [],
    metadata: { purpose: "Onboarding tracks and progress tracking for new users" },
  },
  {
    componentId: "lib-bank-sync",
    type: "LIB",
    name: "Bank Synchronization",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/lib/bank-sync/",
    dependencies: [{ componentId: "integration-gocardless", type: "HARD" }],
    criticalPaths: [],
    metadata: { purpose: "Open banking provider abstraction and transaction sync" },
  },
  {
    componentId: "lib-email-sync",
    type: "LIB",
    name: "Email Synchronization",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/lib/email-sync/",
    dependencies: [
      { componentId: "store-postgresql", type: "HARD" },
      { componentId: "store-r2", type: "SOFT" },
    ],
    criticalPaths: [],
    metadata: { purpose: "Email inbox sync for invoice/receipt import via OAuth" },
  },
  {
    componentId: "lib-stripe",
    type: "LIB",
    name: "Stripe Terminal Utilities",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:billing",
    docsRef: null,
    codeRef: "src/lib/stripe/",
    dependencies: [
      { componentId: "integration-stripe", type: "HARD" },
      { componentId: "store-postgresql", type: "HARD" },
    ],
    criticalPaths: [],
    metadata: { purpose: "Stripe Terminal SDK integration for POS card payments" },
  },
  {
    componentId: "lib-posd",
    type: "LIB",
    name: "PO-SD Calculator",
    status: "STABLE",
    criticality: "HIGH",
    owner: "team:rtl",
    docsRef: null,
    codeRef: "src/lib/posd/",
    dependencies: [],
    criticalPaths: [],
    metadata: { purpose: "PO-SD (paušalni obrt) tax calculation and quarterly breakdown" },
  },
  {
    componentId: "lib-search",
    type: "LIB",
    name: "Search Utilities",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/search/",
    dependencies: [],
    criticalPaths: [],
    metadata: { purpose: "Client-side search with Fuse.js for guides and app content" },
  },
  {
    componentId: "lib-import",
    type: "LIB",
    name: "Import Utilities",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:backend",
    docsRef: null,
    codeRef: "src/lib/import/",
    dependencies: [],
    criticalPaths: [],
    metadata: { purpose: "Document type detection for import (bank statements vs invoices)" },
  },
  {
    componentId: "lib-system-status",
    type: "LIB",
    name: "System Status Utilities",
    status: "STABLE",
    criticality: "MEDIUM",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/system-status/",
    dependencies: [{ componentId: "store-postgresql", type: "HARD" }],
    criticalPaths: [],
    metadata: { purpose: "System registry status snapshots and event tracking" },
  },
  {
    componentId: "lib-marketing-audit",
    type: "LIB",
    name: "Marketing Audit",
    status: "STABLE",
    criticality: "LOW",
    owner: "team:platform",
    docsRef: null,
    codeRef: "src/lib/marketing-audit/",
    dependencies: [],
    criticalPaths: [],
    metadata: { purpose: "Marketing content audit tooling and registry validation" },
  },
]

// =============================================================================
// COMBINED REGISTRY
// =============================================================================

export const ALL_COMPONENTS: SystemComponent[] = [
  ...UI_COMPONENTS,
  ...MODULE_COMPONENTS,
  ...ROUTE_GROUP_COMPONENTS,
  ...WORKER_COMPONENTS,
  ...JOB_COMPONENTS,
  ...QUEUE_COMPONENTS,
  ...STORE_COMPONENTS,
  ...INTEGRATION_COMPONENTS,
  ...LIB_COMPONENTS,
]

/**
 * Get component by ID
 */
export function getComponent(componentId: string): SystemComponent | undefined {
  return ALL_COMPONENTS.find((c) => c.componentId === componentId)
}

/**
 * Get all components of a specific type
 */
export function getComponentsByType(type: SystemComponent["type"]): SystemComponent[] {
  return ALL_COMPONENTS.filter((c) => c.type === type)
}

/**
 * Get all CRITICAL components
 */
export function getCriticalComponents(): SystemComponent[] {
  return ALL_COMPONENTS.filter((c) => c.criticality === "CRITICAL")
}

/**
 * Get components with no owner (governance violation for CRITICAL/HIGH)
 */
export function getUnownedComponents(): SystemComponent[] {
  return ALL_COMPONENTS.filter((c) => c.owner === null)
}

/**
 * Get components in a critical path
 */
export function getComponentsInPath(pathId: string): SystemComponent[] {
  const path = CRITICAL_PATHS.find((p) => p.pathId === pathId)
  if (!path) return []
  return path.components.map((id) => getComponent(id)).filter(Boolean) as SystemComponent[]
}

// =============================================================================
// REGISTRY STATS
// =============================================================================

export const REGISTRY_STATS = {
  totalComponents: ALL_COMPONENTS.length,
  byType: {
    UI: UI_COMPONENTS.length,
    MODULE: MODULE_COMPONENTS.length,
    ROUTE_GROUP: ROUTE_GROUP_COMPONENTS.length,
    WORKER: WORKER_COMPONENTS.length,
    JOB: JOB_COMPONENTS.length,
    QUEUE: QUEUE_COMPONENTS.length,
    STORE: STORE_COMPONENTS.length,
    INTEGRATION: INTEGRATION_COMPONENTS.length,
    LIB: LIB_COMPONENTS.length,
  },
  byCriticality: {
    CRITICAL: ALL_COMPONENTS.filter((c) => c.criticality === "CRITICAL").length,
    HIGH: ALL_COMPONENTS.filter((c) => c.criticality === "HIGH").length,
    MEDIUM: ALL_COMPONENTS.filter((c) => c.criticality === "MEDIUM").length,
    LOW: ALL_COMPONENTS.filter((c) => c.criticality === "LOW").length,
  },
  criticalPaths: CRITICAL_PATHS.length,
  unownedCritical: ALL_COMPONENTS.filter((c) => c.criticality === "CRITICAL" && c.owner === null)
    .length,
}
