-- Add new AuditAction enum values for RTL API operations
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BULK_APPROVE_VIA_API';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BULK_PUBLISH_VIA_API';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'IDEMPOTENCY_CONFLICT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'IDEMPOTENT_REPLAY';
